Recursive dependency linking
virtualcell/vcell pull request #1073
Opened 2023-12-07 16:08 UTC by CodeByDrescher

Fixed issues with linux library linking in recent containers

2023-12-08 16:33 UTC, jcschaff reviewed
is this code exercised by a unit test?  The default GitHub runner is a linux box, and the code should be safe for windows and macos (if tests are run there also).

I imagine that a simple unit test which just runs the local native solvers with no inputs and check for bad return code would work.  later we can run that test on multiple runners (windows, mac, linux).

2023-12-08 16:49 UTC, jcschaff requested changes
add a test for "running" one (or all) native solvers in a basic way (e.g. no args).  This is a blind spot for us so is needed anyway.  We can chat about the easiest way to test this.

2023-12-08 16:49 UTC, jcschaff commented on vcell-core/src/main/java/cbit/vcell/solvers/AbstractCompiledSolver.java
> +        for (File file : temp) {
in the latest java, null pointer exceptions give nice contextual messages.  I you are going to throw a raw NullPointerException, then you might as well let the for loop fail with a nicely formatted NullPointerException.

2026-05-13 19:24 UTC, CodeByDrescher commented
This is very old, and we currently have no problems described here. Closing

2026-05-13 19:24 UTC, closed without merging