Fix Incapability to Export Locally Loaded Simulation Results
virtualcell/vcell pull request #1367
Opened 2024-10-18 18:20 UTC by AvocadoMoon

### Problem
The ExportServiceImpl class declared that it required an N5 related directory which it did not need. This resulted in a required property error being thrown.

### Solution
Remove that required property since it wasn't used, and make it impossible to export N5 files if the simulation is locally loaded onto a clients device.

2024-10-22 17:36 UTC, jcschaff requested changes
can't give complete review, added a comment.  I assume you tested this.

2024-10-22 17:36 UTC, jcschaff commented on vcell-client/src/main/java/cbit/vcell/client/data/PDEExportDataPanel.java
> +		if (!(getPdeDataContext().getVCDataIdentifier() instanceof LocalVCDataIdentifier)){
you may want to guard against NPE if getPdeDataContext() returns null.

2024-10-22 18:47 UTC, AvocadoMoon commented on vcell-client/src/main/java/cbit/vcell/client/data/PDEExportDataPanel.java
> +		if (!(getPdeDataContext().getVCDataIdentifier() instanceof LocalVCDataIdentifier)){
Added a null check for PdeDataContext

2024-11-05 17:33 UTC, jcschaff approved these changes
simple change, approved.

2024-11-05 17:33 UTC, merged